print("=== CYBER ARCHIVES - VAULT SECURITY SYSTEM ===\n")
print("Initiating secure vault access...")
with open("classified_data.txt", "r+") as file:
    print("Vault connection established with failsafe protocols\n")
    print("SECURE EXTRACTION:")
    content = file.read()
    print(content)
    print("\nSECURE PRESERVATION:")
    file.write("\n[CLASSIFIED] New security protocols archived")
    print("[CLASSIFIED] New security protocols archived")
    print("Vault automatically sealed upon completion\n")
print("All vault operations completed with maximum security.")
